### ISSUE TITLE
Select boxes not displayed in payment history

### ISSUE THREAD

**Issue by ghost1227** [easydigitaldownloads/edd-checkout-fields#118]
Select fields aren't being displayed at all in the payment history dialog. As far as I've been able to tell, the info is saving fine, but in the backend it displays the title of the field, but no actual select field or textual display of the saved data.

**Comment by cklosowski** [comment]
I'm not able to replicate this one, could it have been while you also had a 'Repeatable' field prior to it, and caused by #13 ?

![screen shot 2017-05-04 at 4 10 15 pm](https://cloud.githubusercontent.com/assets/1390124/25728479/3e1fbbf2-30e4-11e7-9718-680ba51c6373.png)

**Comment by cklosowski** [comment]
@ghost1227 could you test this without a repeatable field?

**Comment by SDavisMedia** [comment]
I wasn't able to replicate either.

**Comment by cklosowski** [comment]
I'm going to punt this and release, and we can revisit it at a later day and close then if necessary.

**Comment by pippinsplugins** [comment]
This works fine for me.
<img width="607" alt="screen shot 2017-05-09 at 9 46 17 am" src="https://cloud.githubusercontent.com/assets/1034109/25856682/6132bfac-349c-11e7-9c51-215702fc32be.png">

@ghost1227 Could you check your field settings and make sure you have it set to be saved to payment meta and shown in the admin?
<img width="1054" alt="screen shot 2017-05-09 at 9 47 06 am" src="https://cloud.githubusercontent.com/assets/1034109/25856720/799c350a-349c-11e7-999f-9ff4ffec486c.png">

**Comment by ghost1227** [comment]
@pippinsplugins It is set to payment meta/show in admin. However, it's distinctly possible that it was caused by the repeatable field and #13 as @cklosowski suggested. I'll retest.

**Comment by pippinsplugins** [comment]
@ghost1227 confirmed all is working so this can be closed.
