### ISSUE TITLE
Add `required` attributes to required fields

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-checkout-fields#132]
Currently, fields that are supposed to be `required` only have the `required` class on them, so that it get's the class and some custom JS can run against it. To conform to HTML5 spec, and so we can do things like [running form validation via JS](https://github.com/easydigitaldownloads/edd-stripe/issues/142), we need to also add the `required` attribute.

**Comment by SDavisMedia** [comment]
Ticket affected by this: https://secure.helpscout.net/conversation/410727268/64507/?folderId=180499

**Comment by SDavisMedia** [comment]
Sorry for the bump, but I must.

**Comment by SDavisMedia** [comment]
It's almost there! The validation appears to be working as expected now. But for some reason, after the Stripe modal closes, EDD's checkout form throws a cart empty error.

<img width="760" alt="screenshot 2017-08-15 16 58 34" src="https://user-images.githubusercontent.com/2359131/29341712-febe9e5e-81da-11e7-9e12-3de113dbc467.png">

On `issue/132`, I can replicate this on demand. I cannot replicate on `master`.

**Comment by cklosowski** [comment]
I cannot replicate this on `issue/132`. @mintplugins @pippinsplugins mind giving it a shot?

**Comment by mintplugins** [comment]
I'm not getting the empty cart error. On a "normal" payment gateway, everything is working gine. 

However, with `Stripe Checkout` if I leave the required fields blank, after entering my card info into the Stripe Modal, the modal closes and the page just sites there without proceeding to tell me the fields are blank - or sending me to purchase confirmation.

**Comment by cklosowski** [comment]
Cleared. All caches? You should get the notice before the Strips Checkout
opens. I cannot replicate any of this with stripe checkout. It's what I'm
using to test in fact so something is lost in communication somewhere.
Let's screen share Monday.

**Comment by mintplugins** [comment]
Yes all cache is cleared - I'm not getting the notice before the Stripe Checkout opens. 

The required attribute is in place:
<img width="1058" alt="screen shot 2017-08-20 at 12 04 46 pm" src="https://user-images.githubusercontent.com/1638128/29496804-d29d7a98-859f-11e7-8d26-3f378691052b.png">

**Comment by mintplugins** [comment]
Yes EDD master is up to date.

**Comment by cklosowski** [comment]
As a note, the issue was that @mintplugins wasn't on the latest `edd-stripe` `master` branch.

**Comment by mintplugins** [comment]
Yep - I pulled latest `master` on `edd-stripe` and everything is going through correctly for me now on both Stripe Checkout, Stripe regular, and the test payment gateway.

**Comment by cklosowski** [comment]
@SDavisMedia mind testing again, being sure you're on the following pulled latest:
`EDD - master`
`Stripe - master`
`CFM - issue/132`

**Comment by SDavisMedia** [comment]
Yup, still good across the board for me. :+1:
