### ISSUE TITLE
Strip unsupported characters from auto-generated meta keys

### ISSUE THREAD

**Issue by cklosowski** [easydigitaldownloads/edd-checkout-fields#133]
If you put an unsupported meta key character in the Field Label, it auto generates the meta_key with the unsupported character, and saving it give an error:
![error on save](https://cl.ly/2Y2j0A2M123y/Screen%20Shot%202017-08-15%20at%204.04.13%20PM.png)

**Comment by pippinsplugins** [comment]
`sanitize_key` would sold this I believe.

**Comment by cklosowski** [comment]
@pippinsplugins yes, the problem is that we autopopulate it with JS when the person leaves the Field Label input...so we'll have to do it in JS.

**Comment by pippinsplugins** [comment]
PR looks good.
