### ISSUE TITLE
Saved user meta doesn't populate at checkout

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/edd-checkout-fields#138]
If you add a simple text field to the checkout form and have the data save as user meta, though it appears to save the user meta in the DB after the transaction, the value doesn't populate the field the next time you reach the checkout form while logged in.

I get this behavior with all fields I tested.

**Comment by SDavisMedia** [comment]
New ticket: https://secure.helpscout.net/conversation/423540572/65817/?folderId=180499

**Comment by kerijacoby** [comment]
https://secure.helpscout.net/conversation/416585201/65110/?folderId=1448602

**Comment by pippinsplugins** [comment]
@SDavisMedia PR submitted that should fix it.

**Comment by pippinsplugins** [comment]
New PR: https://github.com/easydigitaldownloads/edd-checkout-fields/pull/140

**Comment by SDavisMedia** [comment]
@pippinsplugins that's working as expected for me. Thanks. :+1:
