### ISSUE TITLE
Add upgrade routine for 151

### ISSUE THREAD

**Issue by pippinsplugins** [easydigitaldownloads/edd-checkout-fields#153]
#151 changed the key names for first and last name fields but no upgrade routine was added to migrate old fields to the new keys.

**Comment by pippinsplugins** [comment]
@SDavisMedia could you test this please?

1. Checkout 2.1.1, `git checkout 2.1.1`
2. Set up the form with First and Last name fields
3. `git checkout issue/153`
4. Fields should still be there and work

**Comment by SDavisMedia** [comment]
@pippinsplugins yup the update is working properly and so is the UI on `issue/153`. :+1:
